package main.TCG;

import main.TCG.AI.AbstractAIPlayer;
import main.TCG.Card.Card;
import main.TCG.Card.CreatureCard;
import main.TCG.Card.EffectCard;
import main.TCG.Card.ICreature;
import main.TCG.Events.EventManager;

import java.util.*;

// Some System.out.print statements generated with AI

public class Game {
    private Player player1;
    private Player player2;
    private Scanner scanner = new Scanner(System.in);
    private EventManager eventManager = new EventManager();
    private final int STARTING_HAND_SIZE = 7;
    private final int MAX_HAND_SIZE = 7;

    public Game(Player p1, Player p2) {
        player1 = p1;
        player2 = p2;
        p1.setGame(this);
        p2.setGame(this);
    }

    public void start() {
        System.out.println("\n=== GAME START ===");
        System.out.println(player1.getName() + " vs " + player2.getName());
        System.out.println("Starting HP: " + player1.getHealth() + "\n");

        drawStartingHands(player1);
        drawStartingHands(player2);

        int turnNumber = 1;
        while (!isOver()) {
            // System.out.print Generated by AI
            System.out.println("\n" + "=".repeat(60));
            System.out.println("                       TURN " + turnNumber);
            System.out.println("=".repeat(60));

            takeTurn(player1, player2);
            if (isOver()) break;

            takeTurn(player2, player1);
            if (isOver()) break;

            turnNumber++;
        }

        announceWinner();
    }

    private void drawStartingHands(Player player) {
        System.out.println(player.getName() + " draws starting hand of " + STARTING_HAND_SIZE + " cards.");
        for (int i = 0; i < STARTING_HAND_SIZE; i++) {
            player.drawCard();
        }
    }

    private void takeTurn(Player current, Player opponent) {
        // System.out.print Generated by AI
        System.out.println("\n>>> " + current.getName() + "'s TURN <<<");
        displayGameState(current, opponent);

        untapPhase(current);
        drawPhase(current);

        // While not generated by AI, I copied the style to remain consistent
        System.out.println("\n--- MAIN PHASE 1 ---");
        mainPhase(current, opponent);

        if (isOver()) return;

        System.out.println("\n--- COMBAT PHASE ---");
        combatPhase(current, opponent);

        if (isOver()) return;

        System.out.println("\n--- MAIN PHASE 2 ---");
        mainPhase(current, opponent);

        endPhase(current, opponent);
    }

    // Method generated by AI
    private void displayGameState(Player current, Player opponent) {
        System.out.println("\n" + current.getName() + ": " + current.getHealth() + " HP | " +
                "Hand: " + current.getHand().size() + " | " +
                "Deck: " + current.getDeck().size() + " | " +
                "Battlefield: " + current.getBattlefield().size());
        System.out.println(opponent.getName() + ": " + opponent.getHealth() + " HP | " +
                "Battlefield: " + opponent.getBattlefield().size());
    }

    private void untapPhase(Player current) {
        System.out.println("\n--- UNTAP PHASE ---");
        for (ICreature c : current.getBattlefield()) {
            if (c instanceof CreatureCard creature) {
                creature.startOfTurn();
            }
        }
        System.out.println(current.getName() + " untaps all creatures and clears damage.");
    }

    private void drawPhase(Player current) {
        System.out.println("\n--- DRAW PHASE ---");
        Card drawn = current.drawCard();
        if (drawn != null) {
            System.out.println(current.getName() + " draws a card. (" + current.getHand().size() + " in hand)");
        } else {
            System.out.println(current.getName() + " cannot draw - deck is empty!");
        }
    }

    private void mainPhase(Player current, Player opponent) {
        if (current instanceof AbstractAIPlayer ai) {
            ai.playTurn(opponent);
        } else {
            playCardsInteractive(current, opponent);
        }
    }

    private void playCardsInteractive(Player current, Player opponent) {
        List<Card> hand = current.getHand();
        int cardsPlayed = 0;
        int maxCardsPerTurn = 3;

        while (!hand.isEmpty() && cardsPlayed < maxCardsPerTurn) {
            System.out.println("\nYour hand:");
            for (int i = 0; i < hand.size(); i++) {
                Card card = hand.get(i);
                System.out.print("  " + (i + 1) + ": ");

                if (card instanceof CreatureCard creature) {
                    System.out.println(creature.getName() + " [Creature " +
                            creature.getDamage() + "/" + creature.getHealth() + "]");
                } else if (card instanceof EffectCard effect) {
                    System.out.println(effect.getName() + " [Effect: " +
                            effect.getEffectType() + " = " + effect.getEffectValue() + "]");
                } else {
                    System.out.println(card.getName());
                }
            }

            System.out.println("\nYour battlefield:");
            List<ICreature> battlefield = current.getBattlefield();
            if (battlefield.isEmpty()) {
                System.out.println("  [Empty]");
            } else {
                for (ICreature c : battlefield) {
                    System.out.println("  - " + c.toString());
                }
            }

            System.out.println("\nCards played this phase: " + cardsPlayed + "/" + maxCardsPerTurn);
            System.out.print("Play card (1-" + hand.size() + ") or 0 to end phase: ");
            int choice = getValidInput(0, hand.size());

            if (choice == 0) break;

            Card cardToPlay = hand.get(choice - 1);
            cardToPlay.play(current, opponent);
            hand.remove(cardToPlay);
            cardsPlayed++;
        }

        if (cardsPlayed == maxCardsPerTurn) {
            System.out.println("\nMaximum cards per turn reached (" + maxCardsPerTurn + ").");
        }
    }

    private void combatPhase(Player current, Player opponent) {
        List<CreatureCard> availableAttackers = new ArrayList<>();

        // Find creatures that can attack
        for (ICreature c : current.getBattlefield()) {
            if (c instanceof CreatureCard creature && creature.canAttack()) {
                availableAttackers.add(creature);
            }
        }

        if (availableAttackers.isEmpty()) {
            System.out.println("No creatures available to attack.");
            return;
        }

        // Declare attackers
        List<CreatureCard> attackers = declareAttackers(current, opponent, availableAttackers);

        if (attackers.isEmpty()) {
            System.out.println(current.getName() + " does not attack.");
            return;
        }

        // Declare blockers
        Map<CreatureCard, CreatureCard> blockers = declareBlockers(current, opponent, attackers);

        // Resolve combat
        resolveCombat(current, opponent, attackers, blockers);
    }

    private List<CreatureCard> declareAttackers(Player attacker, Player defender, List<CreatureCard> available) {
        List<CreatureCard> attackers = new ArrayList<>();

        System.out.println("\n=== DECLARE ATTACKERS ===");
        System.out.println("Available creatures:");
        for (int i = 0; i < available.size(); i++) {
            System.out.println("  " + (i + 1) + ": " + available.get(i));
        }

        if (attacker instanceof AbstractAIPlayer) {
            // AI attacks with all available creatures
            attackers.addAll(available);
            for (CreatureCard creature : attackers) {
                creature.setTapped(true);
                System.out.println("  " + creature.getName() + " attacks!");
            }
        } else {
            System.out.print("\nSelect attackers (comma-separated, e.g. 1,3,4) or 0 to skip: ");
            scanner.nextLine();
            String input = scanner.nextLine().trim();

            if (!input.equals("0") && !input.isEmpty()) {
                for (String s : input.split(",")) {
                    try {
                        int idx = Integer.parseInt(s.trim()) - 1;
                        if (idx >= 0 && idx < available.size()) {
                            CreatureCard creature = available.get(idx);
                            creature.setTapped(true);
                            attackers.add(creature);
                            System.out.println("  " + creature.getName() + " attacks!");
                        }
                    } catch (NumberFormatException e) {
                        // Skip invalid input
                    }
                }
            }
        }

        return attackers;
    }

    private Map<CreatureCard, CreatureCard> declareBlockers(Player attacker, Player defender, List<CreatureCard> attackers) {
        Map<CreatureCard, CreatureCard> blockers = new HashMap<>();

        // Find available blockers
        List<CreatureCard> availableBlockers = new ArrayList<>();
        for (ICreature c : defender.getBattlefield()) {
            if (c instanceof CreatureCard creature && creature.canBlock()) {
                availableBlockers.add(creature);
            }
        }

        if (availableBlockers.isEmpty()) {
            System.out.println("\n" + defender.getName() + " has no creatures to block with.");
            return blockers;
        }

        System.out.println("\n=== DECLARE BLOCKERS ===");

        for (CreatureCard attackingCreature : attackers) {
            System.out.println("\nAttacker: " + attackingCreature);
            System.out.println("Available blockers:");

            for (int i = 0; i < availableBlockers.size(); i++) {
                CreatureCard blocker = availableBlockers.get(i);
                if (!blocker.isTapped()) {
                    System.out.println("  " + (i + 1) + ": " + blocker);
                }
            }

            if (defender instanceof AbstractAIPlayer) {
                // AI blocks with first available creature
                for (CreatureCard blocker : availableBlockers) {
                    if (!blocker.isTapped()) {
                        blockers.put(attackingCreature, blocker);
                        blocker.setTapped(true);
                        System.out.println("  " + blocker.getName() + " blocks!");
                        break;
                    }
                }
            } else {
                System.out.print("Block with creature (0 for no block): ");
                int choice = getValidInput(0, availableBlockers.size());

                if (choice > 0) {
                    CreatureCard blocker = availableBlockers.get(choice - 1);
                    if (!blocker.isTapped()) {
                        blockers.put(attackingCreature, blocker);
                        blocker.setTapped(true);
                        System.out.println("  " + blocker.getName() + " blocks!");
                    }
                }
            }
        }

        return blockers;
    }

    public void resolveCombat(Player attackerPlayer, Player defenderPlayer,
                              List<CreatureCard> attackers, Map<CreatureCard, CreatureCard> blockers) {

        System.out.println("\n=== COMBAT RESOLUTION ===");

        for (CreatureCard attacker : attackers) {
            CreatureCard blocker = blockers.get(attacker);

            if (blocker == null) {
                // Unblocked: damage goes to player
                int damage = attacker.getDamage();
                defenderPlayer.takeDamage(damage);
                System.out.println(attacker.getName() + " deals " + damage + " damage to " +
                        defenderPlayer.getName() + " (" + defenderPlayer.getHealth() + " HP remaining)");
            } else {
                // Creature combat: simultaneous damage
                System.out.println(attacker.getName() + " fights " + blocker.getName() + ":");

                attacker.takeCombatDamage(blocker.getDamage());
                blocker.takeCombatDamage(attacker.getDamage());

                // Print results
                if (!attacker.isAlive()) {
                    System.out.println("  " + attacker.getName() + " dies!");
                }
                if (!blocker.isAlive()) {
                    System.out.println("  " + blocker.getName() + " dies!");
                }
            }
        }

        // Remove dead creatures
        attackerPlayer.getBattlefield().removeIf(c -> !((CreatureCard) c).isAlive());
        defenderPlayer.getBattlefield().removeIf(c -> !((CreatureCard) c).isAlive());
    }

    private void endPhase(Player current, Player opponent) {
        System.out.println("\n--- END PHASE ---");

        // Discard down to max hand size
        while (current.getHand().size() > MAX_HAND_SIZE) {
            System.out.println(current.getName() + " must discard to " + MAX_HAND_SIZE + " cards.");

            if (current instanceof AbstractAIPlayer) {
                Card discarded = current.getHand().remove(0);
                System.out.println("  AI discards " + discarded.getName());
            } else {
                System.out.println("\nYour hand:");
                for (int i = 0; i < current.getHand().size(); i++) {
                    System.out.println("  " + (i + 1) + ": " + current.getHand().get(i).getName());
                }
                System.out.print("Discard card: ");
                int choice = getValidInput(1, current.getHand().size());
                Card discarded = current.getHand().remove(choice - 1);
                System.out.println("  You discard " + discarded.getName());
            }
        }

        System.out.println("Turn ends.\n");
    }

    private int getValidInput(int min, int max) {
        while (true) {
            try {
                if (scanner.hasNextInt()) {
                    int choice = scanner.nextInt();
                    if (choice >= min && choice <= max) {
                        return choice;
                    }
                }
                scanner.nextLine();
                System.out.print("Invalid. Enter " + min + "-" + max + ": ");
            } catch (Exception e) {
                scanner.nextLine();
            }
        }
    }

    public boolean isOver() {
        // Player is dead
        if (player1.getHealth() <= 0 || player2.getHealth() <= 0) return true;

        // Player has no cards left
        boolean p1OutOfCards = player1.getHand().isEmpty() && player1.getDeck().isEmpty();
        boolean p2OutOfCards = player2.getHand().isEmpty() && player2.getDeck().isEmpty();

        return p1OutOfCards || p2OutOfCards;
    }

    private void announceWinner() {
        // Copied from above, so it is somewhat generated
        System.out.println("\n" + "=".repeat(60));
        System.out.println("                     GAME OVER");
        System.out.println("=".repeat(60));

        String winner;
        String reason;

        if (player1.getHealth() <= 0) {
            winner = player2.getName();
            reason = player1.getName() + " was defeated!";
        } else if (player2.getHealth() <= 0) {
            winner = player1.getName();
            reason = player2.getName() + " was defeated!";
        } else if (player1.getDeck().isEmpty() && player1.getHand().isEmpty()) {
            winner = player2.getName();
            reason = player1.getName() + " ran out of cards!";
        } else {
            winner = player1.getName();
            reason = player2.getName() + " ran out of cards!";
        }

        System.out.println("\nWINNER: " + winner);
        System.out.println("Reason: " + reason);
        System.out.println("\nFinal Scores:");
        System.out.println("  " + player1.getName() + ": " + player1.getHealth() + " HP");
        System.out.println("  " + player2.getName() + ": " + player2.getHealth() + " HP");
    }

    public EventManager getEventManager() {
        return eventManager;
    }
}